# Welcome to Framer

### values ###

bgcolor = '#000000'
shadowcolor = '#FF0000'

### Use a device ###

device = new (Framer.DeviceComponent)
device.setupContext()
# Display only the device
# device.deviceType = "iphone-5c-pink";
# Display a hand with the device
device.deviceType = 'iphone-5c-pink-hand'
# Change the size
device.setDeviceScale 0.3
# Draw a white square
whiteSquare = new Layer(
  backgroundColor: '' + bgcolor + ''
  width: 400
  height: 120
  y: 0)
# Center horizontally
whiteSquare.centerX()
# Draw an image
#imageLayer = new Layer({x:0, y:0, width:128, height:128, image:"images/Icon.png"})
# imageLayer.center()
pic = new Layer(
  image: 'images/audrey_in_funny_face_audrey_hepburn_400x400.jpg'
  width: 400
  height: 300
  y: 120)
pic.centerX()
# Write text
text = new Layer(
  backgroundColor: '' + bgcolor + ''
  width: Screen.width
  height: 160
  y: 420
  html: 'Who am I ?'
  style:
    fontSize: '20px'
    textAlign: 'center'
    color: '#FFFFFF'
    paddingTop: '15px'
    lineHeight: '50px'
    fontFamily: 'Tahoma, Geneva, sans-serif')
text.on 'click', ->
  text.html = 'This is Audrey Hepburn<br> in Funny Face'
  return
# Animate borderRadius
whiteSquare.animate
  properties: borderRadius: whiteSquare.width / 8
  time: 2
  curve: 'ease-in-out'
# Animate Shadow
whiteSquare.on 'click', ->
  # Set the shadow color first
  whiteSquare.shadowColor = '#555555'
  whiteSquare.animate 'properties':
    shadowBlur: 40
    shadowSpread: 10
  return
# Add two states
pic.states.add
  'myState1': borderRadius: 100
  'myState2': borderRadius: 200
# Change state when clicked
pic.on 'click', ->
  # Switch to myState2
  pic.states.switch 'myState2'
  return
bg = new BackgroundLayer(backgroundColor: '' + bgcolor + '')

# ---
# generated by js2coffee 2.2.0

